from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
OUTPUT_DIR = DATA_DIR / "outputs"
REPORT_DIR = BASE_DIR / "reports"
FIGURES_DIR = REPORT_DIR / "figures"
TABLES_DIR = REPORT_DIR / "tables"

START_DATE = "2010-02-01"
END_DATE = "2025-12-31"
SEED = 42

SEQ_LEN = 60
TRAIN_YEARS = 5
VAL_YEARS = 1
TEST_YEARS = 1
BUSINESS_DAYS_MONTH = 21

VAR_CONF = 0.95
Z_95 = 1.645
PIP_COST = 0.0002

LOW_HEDGE = 0.30
MID_HEDGE = 0.60
HIGH_HEDGE = 0.90

MC_N_SIMS = 2000
MC_MEAN_DAILY_INFLOW = 100000.0
MC_MEAN_DAILY_OUTFLOW = 80000.0
MC_VOL_INFLOW = 0.15
MC_VOL_OUTFLOW = 0.12
MC_CORR = 0.30

YF_TICKERS = {
    "EURUSD": "EURUSD=X",
    "VIX": "^VIX",
    "DXY": "DX-Y.NYB",
    "WTI": "CL=F",
}
FRED_SERIES = {"US10Y": "DGS10"}
ECB_EURO_10Y_DAILY_KEY = "B.U2.EUR.4F.G_N_A.SV_C_YM.SR_10Y"
